Metrics/AbcSize:
  Enabled: false
Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false
  VersionAdded: "0.9"
  AllowedConstants: []
  Exclude:
    - "spec/**/*"
    - "test/**/*"
